### ISSUE TITLE
Adding to Jamf-Custom-Profile-Schemas?

### ISSUE THREAD

**Issue by talkingmoose** [kdrwygvh/JSON-Schema-for-Jamf-Pro-Applications---Settings-MDM-Payload#1]
Would love to see your Jamf Pro manifests included here:
https://github.com/Jamf-Custom-Profile-Schemas

If you reach out to @MScottBlake, he can add you as a contributor. Then you can fork your repository to that project and keep it updated from here using pull requests.

**Comment by kdrwygvh** [comment]
Thanks, will see to it shortly.
